### ISSUE TITLE
release-info has some problems

### ISSUE THREAD

**Issue by sjamaan** [iraikov/picnic#1]
Hi Ivan,

I noticed that picnic is listed in henrietta-cache's output here:

```
http://code.call-cc.org/henrietta-cache/latest-err-4
```

The release-info looks like this:

```
;; -*- scheme -*-
(repo git "git://github.com/iraikov/picnic.git")
(uri targz "https://github.com/iraikov/picnic/tarball/{egg-release}")
(uri files-list "http://code.call-cc.org/files-list?egg={egg-name};release={egg-release}" old-uri)

(release "1.5")
(release "1.4" old-uri)
```

I think this is incorrect in two ways: the `tags` directory in svn doesn't have a 1.4 tag, there's only 1.0, 1.1, 1.2 and 1.3 on call-cc.org.  Secondly, the `files-list` URI should be changed to `http://code.call-cc.org/files-list?egg={egg-name};egg-release={egg-release};chicken-release={chicken-release}`. The `release` parameter doesn't exist anymore, it was renamed long ago to `egg-release`.

The `chicken-release` parameter is currently optional (it is implicitly set to `4`), but it's good practice to start using explicit reference to `4` now that CHICKEN 5 is in development.  We won't change the implicit value to 5, but we might start requiring it later to keep things simple.

So, for a full example, I think the release-info file should look like this:

```
;; -*- scheme -*-
(repo git "git://github.com/iraikov/picnic.git")
(uri targz "https://github.com/iraikov/picnic/tarball/{egg-release}")
(uri files-list "http://code.call-cc.org/files-list?egg={egg-name};egg-release={egg-release};chicken-release={chicken-release}" old-uri)

(release "1.5")
(release "1.4")
(release "1.3" old-uri)
(release "1.2" old-uri)
(release "1.1" old-uri)
(release "1.0" old-uri)
```

**Comment by iraikov** [comment]
Thanks for the report, I will fix this soon, and also my other eggs on
github.
